spring.application.name=mysawit-payment
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5435/mysawit_payment
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
xendit.api.key=${XENDIT_API_KEY}
xendit.api.url=https://api.xendit.co