CREATE TABLE IF NOT EXISTS payrolls (
    id UUID PRIMARY KEY,
    worker_id VARCHAR(255),
    worker_name VARCHAR(255),
    amount NUMERIC(38, 2),
    status VARCHAR(255),
    reference_id VARCHAR(255),
    created_at TIMESTAMP,
    tanggal DATE,
    payroll_type VARCHAR(255),
    description TEXT,
    rejection_reason TEXT,
    approved_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wage_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buruh_wage_per_kg NUMERIC(38, 2) NOT NULL,
    supir_truck_wage_per_kg NUMERIC(38, 2) NOT NULL,
    mandor_wage_per_kg NUMERIC(38, 2) NOT NULL
);
